### ISSUE TITLE
Licence violation in angelobdev/nitro

### ISSUE THREAD

**Issue by Gurkengewuerz** [angelobdev/angelobdev#1]
Hey,

first thanks for forking and using my nitro docker installation. It was at it's time just a setup to try nitro without a hassle.
I release the project under Affero GPL and you changed your fork to the MIT licence. I would ask you to comment on this and explain why you changed the AGPL to the incompatible MIT licence.

**Comment by angelobdev** [comment]
Hi,
first of all your work was awesome. I didn't know that changing license would be a problem, anyway I'm going to change it back to a GPL right away.

**Comment by Gurkengewuerz** [comment]
Thank you. Have fun with the Project. 🙌
